-- Phase 6: Financial Payout Engine (Atomic Transaction RPC)
-- Run this in the Supabase SQL Editor to create the settlement function.
--
-- This function guarantees idempotency and transaction safety. It takes the pre-calculated 
-- ledger rows generated by the TypeScript backend and inserts them atomically while 
-- updating the pod's status. If anything fails, it rolls back instantly.

CREATE OR REPLACE FUNCTION settle_pod_transaction(
  p_pod_id UUID,
  p_ledger_rows JSONB
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_pod RECORD;
  v_row JSONB;
BEGIN
  -- 1. Acquire row-level lock to prevent concurrent cycle-end race conditions
  SELECT * INTO v_pod 
  FROM pods 
  WHERE id = p_pod_id 
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Pod not found';
  END IF;

  -- 2. Idempotency guard: abort silently if already processed
  IF v_pod.status = 'completed' THEN
    RETURN;
  END IF;

  -- 3. Atomically write all computed ledger rows
  FOR v_row IN SELECT * FROM jsonb_array_elements(p_ledger_rows)
  LOOP
    INSERT INTO ledger (pod_id, user_id, type, amount)
    VALUES (
      p_pod_id, 
      (v_row->>'user_id')::UUID, 
      v_row->>'type', 
      (v_row->>'amount')::NUMERIC
    );
  END LOOP;

  -- 4. Mark pod as completely settled
  UPDATE pods SET status = 'completed' WHERE id = p_pod_id;
END;
$$;
